/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;

import java.util.ArrayList;
import java.util.Arrays;

public class App {

    public static void main(String[] args) {

        System.out.println();
        // example - 1: empty list
        testCase(new ArrayList<Integer>(), "Empty list");

        // example - 2: single element
        testCase(new ArrayList<>(Arrays.asList(1)), "One item");

        // example - 3: no duplicates
        testCase(new ArrayList<>(Arrays.asList(1, 2, 3)), "No duplicates");

        // example - 4: string list with duplicates
        testCase(new ArrayList<>(Arrays.asList("A", "A", "B")), "String duplicates");

        // example - 5: int list with multiple duplicates
        testCase(new ArrayList<>(Arrays.asList(1, 1, 3, 3, 5, 5)), "Integer with repeats");

        // example - 6: list with mixed casing (show case sensitivity)
        testCase(new ArrayList<>(Arrays.asList("a", "A", "a", "B", "b")), "Case sensitivity");

        // example - 7: list with all elements the same
        testCase(new ArrayList<>(Arrays.asList("X", "X", "X", "X")), "Same elements");

        // example - 8: list with alternating duplicates
        testCase(new ArrayList<>(Arrays.asList(1, 2, 1, 2, 1, 2)), "Alternating duplicates");

        // example - 9: list with nulls (if allowed)
        testCase(new ArrayList<>(Arrays.asList(null, "Z", null, "Z")), "Including nulls");

        // example - 9: large list with ordered and unordered duplicates
        testCase(new ArrayList<>(Arrays.asList(3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5)), "Large mixed");

    }

    // helper method to run test case
    private static <T> void testCase(ArrayList<T> input, String description) {
        System.out.println(description + ":-");
        System.out.println("Original: " + input);

        // call method to remove duplicates
        ArrayList<T> result = RemoveDuplicate.removeDuplicates(input);

        System.out.println("No duplicates: " + result);
        System.out.println(); // for spacing
    }
}
